name: Build Windows
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
      - name: Checkout FFmpeg
        uses: actions/checkout@v3
        with:
          repository: FFmpeg/FFmpeg
          path: FFmpeg
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            coreutils
            gawk
            make
            diffutils
            yasm
            nasm
      - name: build
        run: node ./build.js
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: output